#!/usr/bin/env node
/**
 * Per-page SEO metadata check over the prerendered output.
 *
 * Fails when a page is missing a <title>, a <meta name="description">, or a
 * <link rel="canonical">, and when two pages share a title or a description.
 *
 * The duplicate half is the one that actually catches things. Every page is
 * built by script/prerender.ts from the same dist/public/index.html template
 * and gets its metadata by regex substitution over that template. When a new
 * route is added with writePage() but its title or description is left at the
 * default, or a substitution silently misses, the page inherits the home
 * page's metadata instead of failing. The output looks fine; two URLs just
 * quietly compete for the same query, and a crawler picks one.
 *
 * Usage: node scripts-ci/check-meta.mjs   (after npm run build)
 */

import { readFileSync, readdirSync, existsSync } from "node:fs";
import path from "node:path";

const DIST = path.resolve("dist/public");

function fail(message) {
  console.error(`\nFAIL  ${message}\n`);
  process.exit(1);
}

if (!existsSync(DIST)) {
  fail(`dist/public not found. Run "npm run build" first.`);
}

function htmlFiles(dir, found = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) htmlFiles(full, found);
    else if (entry.name.endsWith(".html")) found.push(full);
  }
  return found;
}

/** The route a file is served at, for readable error messages. */
function routeOf(file) {
  const relative = path.relative(DIST, file);
  if (relative === "index.html") return "/";
  // Pages are emitted flat as <path>.html; 404.html keeps its name because
  // Cloudflare looks for it by that exact filename.
  if (relative === "404.html") return "/404.html";
  return `/${relative.replace(/\.html$/, "").replace(/(?:^|\/)index$/, "")}`;
}

const pages = htmlFiles(DIST);
if (pages.length === 0) {
  fail("No HTML files in dist/public. The prerender step did not run.");
}

const titles = new Map();
const descriptions = new Map();
const missing = [];

for (const file of pages) {
  const html = readFileSync(file, "utf8");
  const route = routeOf(file);

  const title = (html.match(/<title>([\s\S]*?)<\/title>/) || [])[1]?.trim();
  const description = (
    html.match(/<meta\s+name="description"\s+content="([^"]*)"/i) || []
  )[1]?.trim();
  const canonical = (
    html.match(/<link\s+rel="canonical"\s+href="([^"]*)"/i) || []
  )[1]?.trim();

  /*
    404.html is the one page with no canonical, on purpose.

    It is served for URLs that do not exist, so there is no address it could
    honestly point at. Claiming one would either name a page that also does
    not exist, or tell Google this content lives at some real URL. It carries
    noindex instead, which is the correct signal, and Google ignores canonical
    on a non-200 response anyway. It still needs a title and a description.
  */
  const isNotFoundPage = route === "/404.html";

  const absent = [];
  if (!title) absent.push("title");
  if (!description) absent.push("description");
  if (!canonical && !isNotFoundPage) absent.push("canonical");
  if (absent.length > 0) missing.push(`  ${route}  missing: ${absent.join(", ")}`);

  if (title) titles.set(title, [...(titles.get(title) || []), route]);
  if (description) {
    descriptions.set(description, [...(descriptions.get(description) || []), route]);
  }
}

const duplicates = (map, label) =>
  [...map.entries()]
    .filter(([, routes]) => routes.length > 1)
    .map(([value, routes]) => {
      const snippet = value.length > 70 ? `${value.slice(0, 70)}...` : value;
      return `  ${label} "${snippet}"\n      shared by: ${routes.join(", ")}`;
    });

const duplicateTitles = duplicates(titles, "title");
const duplicateDescriptions = duplicates(descriptions, "description");

console.log(
  `Checked ${pages.length} prerendered pages: ` +
    `${titles.size} distinct titles, ${descriptions.size} distinct descriptions.`,
);

/*
  Every og:image and twitter:image must resolve to a file that exists.

  A broken social card is invisible from inside the site: the page renders
  perfectly, and the only symptom is that a shared link shows nothing. The
  cards are generated by scripts-ci/make-og-images.py and committed, so the
  failure mode is real: add a page to STANDALONE, forget to regenerate, and
  the HTML points at an image that was never written.
*/
const SITE = "https://maxdoubin.com";
const brokenCards = [];
const seenCard = new Set();
for (const file of pages) {
  const html = readFileSync(file, "utf8");
  const rel = path.relative(DIST, file);
  for (const prop of ['property="og:image"', 'name="twitter:image"']) {
    const m = html.match(new RegExp(`<meta ${prop} content="([^"]*)"`));
    if (!m) continue;
    const url = m[1];
    if (!url) {
      brokenCards.push(`  ${rel}: empty ${prop}`);
      continue;
    }
    if (!url.startsWith(SITE + "/")) {
      brokenCards.push(`  ${rel}: ${prop} is not an absolute ${SITE} URL: ${url}`);
      continue;
    }
    const asset = url.slice(SITE.length + 1);
    const key = `${rel}|${asset}`;
    if (seenCard.has(key)) continue;
    seenCard.add(key);
    if (!existsSync(path.join(DIST, asset))) {
      brokenCards.push(`  ${rel}: ${prop} points at a missing file: /${asset}`);
    }
  }
}

/*
  Claims that must never reappear in the built output.

  The site described a 10th grader as a "nationally recognized cybersecurity
  specialist and enterprise networking expert" with jobTitle "Cybersecurity
  Specialist", on all 331 pages, in the machine readable Person node that an
  assistant or a search engine quotes when asked who he is. The FAQ on the
  same site correctly said "10th-grade cybersecurity student", so the site
  contradicted itself.

  "Specialist" itself is fine and is Max's own choice of word: it describes
  a focus, not an employer, and the work behind it is real. What is banned is
  "nationally recognized", which asserted a standing with nothing behind it,
  and the jobTitle field, which in schema.org means employment.

  The replacement says "nationally ranked" instead, which is a fact anyone
  can ask him to evidence: his National Cyber League scouting report puts him
  in the 99th percentile nationally.

  A later revision claimed "Diamond Tier 1, the highest division and tier".
  That is banned below. The scouting report awards no division at all: it
  reports a rank and a percentile, and the words Diamond, tier, bracket and
  division appear nowhere in its eight pages. A credential nobody issued is
  the one kind of claim that cannot survive being checked.

  This is a truthfulness gate, not a style one. An admissions officer who
  spots one inflated claim discounts every honest one next to it.
*/
const FORBIDDEN = [
  ["nationally recognized", "implies a standing a 10th grader does not have"],
  ['"jobTitle": "Cybersecurity Specialist"', "he is a student, not an employee"],
  ['name="twitter:site"', "claims an X account that siteConfig.social does not list"],
  ["Diamond Tier", "the NCL scouting report awards no division or tier"],
  ["Diamond Division", "the NCL scouting report awards no division or tier"],
];

const forbidden = [];
for (const file of pages) {
  const html = readFileSync(file, "utf8");
  const rel = path.relative(DIST, file);
  for (const [needle, why] of FORBIDDEN) {
    if (html.includes(needle)) forbidden.push(`  ${rel}: ${needle}  (${why})`);
  }
}

const problems = [];
if (forbidden.length > 0) {
  const shown = forbidden.slice(0, 6).join("\n");
  problems.push(
    `${forbidden.length} page(s) carry a claim that was deliberately removed:\n${shown}` +
      (forbidden.length > 6 ? `\n  ...and ${forbidden.length - 6} more` : ""),
  );
}
if (brokenCards.length > 0) {
  problems.push(
    `${brokenCards.length} broken social card reference(s):\n${brokenCards.slice(0, 15).join("\n")}` +
      (brokenCards.length > 15 ? `\n  ...and ${brokenCards.length - 15} more` : "") +
      `\n\n  Regenerate with: python3 scripts-ci/make-og-images.py`,
  );
}
if (missing.length > 0) {
  problems.push(`${missing.length} page(s) with missing metadata:\n${missing.join("\n")}`);
}
if (duplicateTitles.length > 0) {
  problems.push(`${duplicateTitles.length} duplicate title(s):\n${duplicateTitles.join("\n")}`);
}
if (duplicateDescriptions.length > 0) {
  problems.push(
    `${duplicateDescriptions.length} duplicate description(s):\n${duplicateDescriptions.join("\n")}`,
  );
}

if (problems.length > 0) {
  fail(
    `${problems.join("\n\n")}\n\n` +
      `  Each route needs its own title, description and canonical, set in ` +
      `script/prerender.ts\n  (or in the page's useSEO call for routes that ` +
      `are not prerendered).`,
  );
}

console.log(
  "\nOK  every page has a unique title, a unique description, a canonical, " +
    "and a social card that resolves.",
);
