/**
 * What each part of the Cisco 42U model is.
 *
 * Same discipline as the rest of the library, and one Cisco-specific rule
 * that matters here more than anywhere: Cisco publish power supply ratings
 * and PoE budgets, not the device's own draw. A 715W supply is not a 715W
 * switch. So `watts` is null on everything in this rack, which renders as
 * "not published", which is true.
 *
 * Rack unit heights are Cisco's published figures, not estimates. The
 * 9404R is 6RU and the UCS 5108 is 6RU with eight half-width bays over
 * four front-accessible supplies; both are cited below.
 */

import type { HeroPart } from "./types";

export const CISCO_SCENERY = new Set([
  "RACK_FRAME",
  "RACK_HOLES",
  "MOUNTING_RAILS",
  "SIDE_BRACES",
  "FRAME_EDGE_HIGHLIGHTS",
  "SHELF_FEET",
  "PATCH_CABLES_WHITE",
  "PATCH_CABLES_BLUE",
  "BLUE_UPLINKS",
  "LONG_WHITE_SERVICE_CABLE",
  "world",
]);

const ACCENT = {
  access: "#ffa114",
  core: "#ccff00",
  spine: "#4cf1f1",
  edge: "#7c9cff",
  compute: "#4ef08a",
  passive: "#8a93a6",
  power: "#9234ea",
};

/** Every powered device here: Cisco publish supply ratings, not draw. */
const W = null;

export const CISCO_PARTS: HeroPart[] = [
  {
    group: "PATCH_PANEL_A",
    device: {
      id: "PATCH_PANEL_A",
      u: 1,
      vendor: "Generic",
      model: "24-port keystone patch panel A",
      role: "Positions A01 to A24, cross-connected to the 9300 below. In a tidy closet the panel position and the wall jack number match, which is the whole trick to tracing a drop in seconds.",
      family: "patch",
      finish: "dark",
      watts: W,
      accent: ACCENT.passive,
    },
  },
  {
    group: "C9300_48P",
    device: {
      id: "C9300_48P",
      u: 1,
      vendor: "Cisco",
      model: "Catalyst 9300-48P with C9300-NM-8X uplink module",
      role: "The access switch: 48 PoE+ ports for desks, phones, cameras and access points, in the two rows a dense copper panel uses, with the modular bay at the far right carrying eight 10G SFP+ uplinks. Beacon and status LEDs sit at the far left, which is where every switch in the family puts them.",
      family: "switch",
      finish: "light",
      portTint: "#1c6f6a",
      groupsOf: 6,
      moduleBay: true,
      watts: W,
      accent: ACCENT.access,
      url: "https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-9300-series-switches/nb-06-cat9300-ser-data-sheet-cte-en.html",
    },
  },
  {
    group: "PATCH_PANEL_B",
    device: {
      id: "PATCH_PANEL_B",
      u: 1,
      vendor: "Generic",
      model: "24-port keystone patch panel B",
      role: "Positions B01 to B24 for the second tray. Fourteen are punched down; the open keystones are capacity for the next reshuffle, which is cheaper to buy now than to retrofit later.",
      family: "patch",
      finish: "dark",
      watts: W,
      accent: ACCENT.passive,
    },
  },
  {
    group: "C9300_24P",
    device: {
      id: "C9300_24P",
      u: 1,
      vendor: "Cisco",
      model: "Catalyst 9300-24P with C9300-NM-4G uplink module",
      role: "The overflow switch: 24 PoE+ ports in a single row, with four gigabit SFP uplinks in the module bay. Half the port count of its neighbour and the same everything else, which is how a closet grows without a forklift.",
      family: "switch",
      finish: "light",
      portTint: "#1c6f6a",
      groupsOf: 6,
      moduleBay: true,
      watts: W,
      accent: ACCENT.access,
      url: "https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-9300-series-switches/nb-06-cat9300-ser-data-sheet-cte-en.html",
    },
  },
  {
    group: "C9500_48Y4C",
    device: {
      id: "C9500_48Y4C",
      u: 1,
      vendor: "Cisco",
      model: "Catalyst 9500-48Y4C",
      role: "The core, and there is no copper on it at all: 48 SFP28 cages running at 25G and four QSFP28 at 100G. Everything in this rack that matters converges here, over fibre, and the absence of a single RJ45 is the fastest way to tell a core switch from an access switch across a room.",
      family: "switch",
      finish: "light",
      portTint: "#1c6f6a",
      watts: W,
      accent: ACCENT.core,
      url: "https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-9500-series-switches/nb-06-cat9500-ser-data-sheet-cte-en.html",
    },
  },
  {
    group: "NEXUS_9336C",
    device: {
      id: "NEXUS_9336C",
      u: 1,
      vendor: "Cisco",
      model: "Nexus 9336C-FX2",
      role: "The spine: 36 QSFP28 cages, every one of them 100G, in a black chassis rather than the Catalyst grey. Nexus is the data centre line and it looks like a different company's product on purpose, which is a real thing to learn from a rack.",
      family: "switch",
      finish: "black",
      watts: W,
      accent: ACCENT.spine,
      url: "https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-742284.html",
    },
  },
  {
    group: "C9404R",
    device: {
      id: "C9404R",
      u: 6,
      vendor: "Cisco",
      model: "Catalyst 9404R modular chassis",
      role: "Six rack units of modular switch: four horizontal slots, of which the middle two take supervisor engines and the outer two take line cards, over a power bay with its own supplies and fans. This is the shape that makes a rack read as Cisco. When a line card dies you pull one card, not one switch.",
      family: "switch",
      finish: "light",
      portTint: "#1c6f6a",
      watts: W,
      accent: ACCENT.core,
      url: "https://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst9400/hardware/install/b_c9400_hig/b_c9400_hig_chapter_0110.html",
    },
  },
  {
    group: "ASR_1001X",
    device: {
      id: "ASR_1001X",
      u: 1,
      vendor: "Cisco",
      model: "ASR 1001-X",
      role: "The WAN aggregation router. Six SFP ports and built-in gigabit copper, sized for a campus handoff rather than a branch office.",
      family: "router",
      finish: "light",
      portTint: "#1c6f6a",
      watts: W,
      accent: ACCENT.edge,
      url: "https://www.cisco.com/c/en/us/products/collateral/routers/asr-1000-series-aggregation-services-routers/datasheet-c78-731640.html",
    },
  },
  {
    group: "ISR_4451X",
    device: {
      id: "ISR_4451X",
      u: 2,
      vendor: "Cisco",
      model: "ISR 4451-X",
      role: "The branch router: onboard gigabit copper and SFP across the top, and four NIM bays along the bottom for whatever the carrier hands over. Two are populated here and two are blanked, which is what a router looks like a year after it was specified.",
      family: "router",
      finish: "light",
      portTint: "#1c6f6a",
      watts: W,
      accent: ACCENT.edge,
      url: "https://www.cisco.com/c/en/us/products/collateral/routers/4000-series-integrated-services-routers-isr/data_sheet-c78-732542.html",
    },
  },
  {
    group: "FIREPOWER_2140",
    device: {
      id: "FIREPOWER_2140",
      u: 1,
      vendor: "Cisco",
      model: "Firepower 2140",
      role: "The firewall, sitting between the routers and everything else. Twelve copper interfaces and four SFP+, in the same near-black as the Nexus rather than Catalyst grey.",
      family: "firewall",
      finish: "black",
      watts: W,
      accent: ACCENT.edge,
      url: "https://www.cisco.com/c/en/us/products/collateral/security/firepower-2100-series/datasheet-c78-742473.html",
    },
  },
  {
    group: "UCS_5108",
    device: {
      id: "UCS_5108",
      u: 6,
      vendor: "Cisco",
      model: "UCS 5108 blade server chassis",
      role: "Six rack units carrying eight half-width blade servers over four hot-swappable supplies, all accessible from the front. A blade chassis is the densest compute in the rack and the least like anything else in it: no ports on the front at all, just servers and power.",
      family: "server",
      finish: "dark",
      bays: { count: 8, occupied: 8, label: "half-width blade bays" },
      watts: W,
      accent: ACCENT.compute,
      url: "https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-5100-series-blade-server-chassis/data_sheet_c78-526830.html",
    },
  },
  {
    group: "UCS_C240",
    device: {
      id: "UCS_C240",
      u: 2,
      vendor: "Cisco",
      model: "UCS C240 rack server",
      role: "Two rack units of storage-dense compute: twenty four small form factor bays in a three by eight grid, with the control panel and KVM on the right. Where a blade gives you density, this gives you spindles.",
      family: "server",
      finish: "dark",
      bays: { count: 24, occupied: 18, label: "2.5 inch bays" },
      watts: W,
      accent: ACCENT.compute,
      url: "https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-c240-m7-rack-server/index.html",
    },
  },
  {
    group: "UCS_C220_A",
    device: {
      id: "UCS_C220_A",
      u: 1,
      vendor: "Cisco",
      model: "UCS C220 rack server",
      role: "One rack unit, ten small form factor bays in a single row. The general purpose workhorse: virtualisation hosts, controllers, anything that needs cores rather than disks.",
      family: "server",
      finish: "dark",
      bays: { count: 10, occupied: 8, label: "2.5 inch bays" },
      watts: W,
      accent: ACCENT.compute,
      url: "https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-c220-m7-rack-server/index.html",
    },
  },
  {
    group: "UCS_C220_B",
    device: {
      id: "UCS_C220_B",
      u: 1,
      vendor: "Cisco",
      model: "UCS C220 rack server",
      role: "The second node. Two identical servers rather than one large one is how a cluster survives losing a server, and it is the cheapest redundancy in the rack.",
      family: "server",
      finish: "dark",
      bays: { count: 10, occupied: 8, label: "2.5 inch bays" },
      watts: W,
      accent: ACCENT.compute,
      url: "https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-c220-m7-rack-server/index.html",
    },
  },
  {
    group: "CABLE_MANAGER_TOP",
    device: {
      id: "CABLE_MANAGER_TOP",
      u: 1,
      vendor: "Generic",
      model: "Horizontal cable manager",
      role: "One rack unit of D-rings between the access switches and the core. The difference between this rack and a bad one is mostly this panel.",
      family: "blank",
      look: "fingers",
      finish: "dark",
      watts: W,
      accent: ACCENT.passive,
    },
  },
  {
    group: "CABLE_MANAGER_MID",
    device: {
      id: "CABLE_MANAGER_MID",
      u: 1,
      vendor: "Generic",
      model: "Horizontal cable manager",
      role: "The second manager, below the spine, keeping the fibre runs off the copper ones. Fibre has a real minimum bend radius and a manager is how you respect it.",
      family: "blank",
      look: "fingers",
      finish: "dark",
      watts: W,
      accent: ACCENT.passive,
    },
  },
  {
    group: "CISCO_PDU",
    device: {
      id: "CISCO_PDU",
      u: 2,
      vendor: "Generic",
      model: "Switched rack PDU, 16 outlets",
      role: "Mains distribution with per-outlet switching. Being able to power cycle one outlet remotely is the difference between a five minute fix and a drive to site.",
      family: "pdu",
      finish: "black",
      display: "ups",
      watts: W,
      accent: ACCENT.power,
    },
  },
  {
    group: "CISCO_UPS",
    device: {
      id: "CISCO_UPS",
      u: 4,
      vendor: "Generic",
      model: "Rack UPS with external battery tray",
      role: "Four rack units of ride-through: the electronics above, the battery tray below with its own handle because batteries are the part that gets replaced. Its draw depends entirely on the load it carries, so no single consumption figure would be honest.",
      family: "ups",
      finish: "black",
      display: "ups",
      watts: W,
      accent: ACCENT.power,
    },
  },
];
