/**
 * MAC address normaliser, OUI lookup, and first-octet bit decoder.
 *
 * The vendor table is a curated subset of the IEEE registry, not a copy of
 * it: roughly ninety prefixes that are worth recognising on sight, weighted
 * towards hypervisors and network gear. The page says so, because a partial
 * table that pretends to be complete is worse than no table.
 */

import { useMemo, useState } from "react";
import { CopyButton } from "@/components/ui/copy-button";
import { ToolPanel, ToolResult, ToolShell } from "./ToolShell";

interface OuiEntry {
  oui: string;
  vendor: string;
  note?: string;
}

const OUI_TABLE: OuiEntry[] = [
  // Hypervisors and containers. These are the ones worth knowing cold,
  // because they tell you what a host is before you have logged into it.
  { oui: "00:50:56", vendor: "VMware", note: "Assigned by vCenter or set by hand on ESXi" },
  { oui: "00:0C:29", vendor: "VMware", note: "Auto-generated by ESXi and Workstation" },
  { oui: "00:05:69", vendor: "VMware", note: "Legacy ESX" },
  { oui: "00:1C:14", vendor: "VMware" },
  { oui: "08:00:27", vendor: "Oracle VirtualBox", note: "Registered to PCS Systemtechnik" },
  { oui: "0A:00:27", vendor: "Oracle VirtualBox", note: "Host-only adapter, locally administered" },
  { oui: "52:54:00", vendor: "QEMU / KVM", note: "Locally administered by design" },
  { oui: "00:16:3E", vendor: "Xen" },
  { oui: "00:15:5D", vendor: "Microsoft Hyper-V" },
  { oui: "00:03:FF", vendor: "Microsoft", note: "Virtual PC and early Hyper-V" },
  { oui: "00:1C:42", vendor: "Parallels" },
  { oui: "00:50:F2", vendor: "Microsoft" },

  // Network equipment.
  { oui: "00:00:0C", vendor: "Cisco Systems" },
  { oui: "00:0C:41", vendor: "Cisco-Linksys", note: "The WRT54G era" },
  { oui: "00:1D:7E", vendor: "Cisco-Linksys" },
  { oui: "00:25:9C", vendor: "Cisco-Linksys" },
  { oui: "00:04:5A", vendor: "Linksys" },
  { oui: "00:06:25", vendor: "Linksys" },
  { oui: "00:05:85", vendor: "Juniper Networks" },
  { oui: "2C:6B:F5", vendor: "Juniper Networks" },
  { oui: "24:A4:3C", vendor: "Ubiquiti" },
  { oui: "04:18:D6", vendor: "Ubiquiti" },
  { oui: "78:8A:20", vendor: "Ubiquiti" },
  { oui: "44:D9:E7", vendor: "Ubiquiti" },
  { oui: "F0:9F:C2", vendor: "Ubiquiti" },
  { oui: "80:2A:A8", vendor: "Ubiquiti" },
  { oui: "74:83:C2", vendor: "Ubiquiti" },
  { oui: "FC:EC:DA", vendor: "Ubiquiti" },
  { oui: "00:15:6D", vendor: "Ubiquiti", note: "Older AirMax radios" },
  { oui: "00:27:22", vendor: "Ubiquiti" },
  { oui: "00:09:5B", vendor: "Netgear" },
  { oui: "00:14:6C", vendor: "Netgear" },
  { oui: "20:4E:7F", vendor: "Netgear" },
  { oui: "00:0F:B5", vendor: "Netgear" },
  { oui: "00:1D:0F", vendor: "TP-Link" },
  { oui: "50:C7:BF", vendor: "TP-Link" },
  { oui: "14:CC:20", vendor: "TP-Link" },
  { oui: "00:80:C8", vendor: "D-Link" },
  { oui: "00:1B:11", vendor: "D-Link" },
  { oui: "00:0D:B9", vendor: "PC Engines", note: "APU and ALIX boards" },
  { oui: "00:04:F2", vendor: "Polycom" },
  { oui: "80:5E:C0", vendor: "Yealink" },
  { oui: "00:0B:82", vendor: "Grandstream" },
  { oui: "00:17:88", vendor: "Signify (Philips Hue)" },

  // Servers, laptops, and NICs.
  { oui: "00:14:22", vendor: "Dell" },
  { oui: "00:21:9B", vendor: "Dell" },
  { oui: "00:1E:C9", vendor: "Dell" },
  { oui: "18:03:73", vendor: "Dell" },
  { oui: "B8:2A:72", vendor: "Dell" },
  { oui: "F8:BC:12", vendor: "Dell" },
  { oui: "00:1B:78", vendor: "Hewlett-Packard" },
  { oui: "3C:D9:2B", vendor: "Hewlett-Packard" },
  { oui: "00:1B:21", vendor: "Intel" },
  { oui: "00:1E:67", vendor: "Intel" },
  { oui: "00:24:D7", vendor: "Intel" },
  { oui: "00:AA:00", vendor: "Intel", note: "One of Intel's original assignments" },
  { oui: "00:E0:4C", vendor: "Realtek", note: "Very common on cheap USB adapters" },
  { oui: "00:1D:60", vendor: "ASUSTek" },
  { oui: "00:1F:C6", vendor: "ASUSTek" },
  { oui: "AC:22:0B", vendor: "ASUSTek" },
  { oui: "00:15:99", vendor: "Samsung Electronics" },
  { oui: "00:1A:11", vendor: "Google" },
  { oui: "F4:F5:D8", vendor: "Google" },

  // Apple.
  { oui: "00:03:93", vendor: "Apple" },
  { oui: "00:0A:27", vendor: "Apple" },
  { oui: "00:1B:63", vendor: "Apple" },
  { oui: "00:1E:C2", vendor: "Apple" },
  { oui: "00:1F:F3", vendor: "Apple" },
  { oui: "00:23:DF", vendor: "Apple" },
  { oui: "00:25:00", vendor: "Apple" },
  { oui: "00:26:BB", vendor: "Apple" },
  { oui: "3C:07:54", vendor: "Apple" },
  { oui: "40:6C:8F", vendor: "Apple" },
  { oui: "68:A8:6D", vendor: "Apple" },
  { oui: "A4:5E:60", vendor: "Apple" },
  { oui: "AC:BC:32", vendor: "Apple" },
  { oui: "F0:18:98", vendor: "Apple" },

  // Single-board computers and IoT silicon.
  { oui: "B8:27:EB", vendor: "Raspberry Pi Foundation", note: "Pi 1 through Pi 3" },
  { oui: "DC:A6:32", vendor: "Raspberry Pi Trading", note: "Pi 4 era" },
  { oui: "E4:5F:01", vendor: "Raspberry Pi Trading", note: "Pi 4 and Pi 400" },
  { oui: "28:CD:C1", vendor: "Raspberry Pi Trading" },
  { oui: "18:FE:34", vendor: "Espressif", note: "ESP8266" },
  { oui: "5C:CF:7F", vendor: "Espressif", note: "ESP8266" },
  { oui: "24:0A:C4", vendor: "Espressif", note: "ESP32" },
  { oui: "30:AE:A4", vendor: "Espressif", note: "ESP32" },
  { oui: "84:F3:EB", vendor: "Espressif" },
  { oui: "A4:CF:12", vendor: "Espressif" },

  // Historical, and still visible in old captures and textbooks.
  { oui: "08:00:20", vendor: "Sun Microsystems" },
  { oui: "08:00:2B", vendor: "Digital Equipment Corporation" },
  { oui: "08:00:69", vendor: "Silicon Graphics" },
  { oui: "00:00:5E", vendor: "IANA", note: "Reserved for protocol use, including VRRP" },
];

const OUI_MAP = new Map(OUI_TABLE.map((entry) => [entry.oui, entry]));

/** Reserved group addresses and virtual-MAC conventions, checked before the OUI table. */
function specialUse(hex: string): string | null {
  if (hex === "FFFFFFFFFFFF") {
    return "The Ethernet broadcast address. Every station on the segment accepts it.";
  }
  if (hex.startsWith("00000C07AC")) {
    return "HSRP version 1 virtual MAC. The last byte is the standby group number.";
  }
  if (hex.startsWith("00000C9FF")) {
    return "HSRP version 2 virtual MAC for IPv4. The final three nibbles are the group number.";
  }
  if (hex.startsWith("00005E0001")) {
    return "VRRP virtual router MAC. The last byte is the virtual router ID.";
  }
  if (hex.startsWith("00005E0002")) {
    return "VRRP for IPv6 virtual router MAC. The last byte is the virtual router ID.";
  }
  if (hex.startsWith("01005E")) {
    return "IPv4 multicast, mapped per RFC 1112: the low 23 bits of the group address are copied into the low 23 bits of the MAC.";
  }
  if (hex.startsWith("3333")) {
    return "IPv6 multicast, mapped per RFC 2464: the low 32 bits of the IPv6 group address become the last four bytes.";
  }
  if (hex.startsWith("0180C2")) {
    return "Reserved by IEEE 802.1. 01:80:C2:00:00:00 is spanning tree, ...:00:00:01 is a pause frame, and ...:00:00:0E is LLDP.";
  }
  if (hex.startsWith("01000C")) {
    return "Cisco protocol multicast. 01:00:0C:CC:CC:CC carries CDP, VTP, UDLD, and PAgP.";
  }
  if (hex.startsWith("0242")) {
    return "Docker. The default bridge assigns 02:42 followed by the container's IPv4 address, and the 02 makes it locally administered.";
  }
  return null;
}

/* --------------------------------------------------------------- parsing */

type Parsed =
  | { kind: "empty" }
  | { kind: "hint"; message: string }
  | { kind: "error"; message: string }
  | { kind: "oui"; hex: string }
  | { kind: "full"; hex: string };

function parseMac(raw: string): Parsed {
  const text = raw.trim();
  if (!text) return { kind: "empty" };
  if (/[^0-9a-fA-F:.\-\s]/.test(text)) {
    return {
      kind: "error",
      message: "Only hex digits and the usual separators (colons, hyphens, dots, spaces) are allowed.",
    };
  }
  const hex = text.replace(/[^0-9a-fA-F]/g, "").toUpperCase();
  if (hex.length === 12) return { kind: "full", hex };
  if (hex.length === 6) return { kind: "oui", hex };
  if (hex.length < 6) return { kind: "hint", message: "Keep going: 6 hex digits for an OUI, 12 for a full address." };
  if (hex.length < 12) {
    return { kind: "hint", message: `${hex.length} hex digits so far. A full MAC address needs 12.` };
  }
  return {
    kind: "error",
    message: `That is ${hex.length} hex digits. A MAC address is 12 (48 bits), or 6 for an OUI on its own.`,
  };
}

function bytesOf(hex: string): string[] {
  return hex.match(/.{2}/g) ?? [];
}

function toEui64(hex: string): string {
  const bytes = bytesOf(hex);
  // Modified EUI-64 inserts FFFE in the middle and inverts the U/L bit, so a
  // globally unique MAC becomes a "locally administered" looking identifier.
  const flipped = (parseInt(bytes[0], 16) ^ 0x02).toString(16).padStart(2, "0").toUpperCase();
  const parts = [flipped, ...bytes.slice(1, 3), "FF", "FE", ...bytes.slice(3)];
  const joined = parts.join("");
  return (joined.match(/.{4}/g) ?? []).join(":").toLowerCase();
}

export function MacLookup() {
  const [raw, setRaw] = useState("B8:27:EB:1A:2B:3C");
  const [tableQuery, setTableQuery] = useState("");

  const parsed = useMemo(() => parseMac(raw), [raw]);
  const hex = parsed.kind === "full" || parsed.kind === "oui" ? parsed.hex : null;

  const decoded = useMemo(() => {
    if (!hex) return null;
    const bytes = bytesOf(hex);
    const first = parseInt(bytes[0], 16);
    const ouiHex = hex.slice(0, 6);
    const oui = (ouiHex.match(/.{2}/g) ?? []).join(":");
    const entry = OUI_MAP.get(oui);
    const locallyAdministered = (first & 0x02) !== 0;
    return {
      bytes,
      first,
      firstBits: first.toString(2).padStart(8, "0"),
      oui,
      entry,
      multicast: (first & 0x01) !== 0,
      locallyAdministered,
      nic: hex.length === 12 ? bytes.slice(3).join(":") : null,
      special: hex.length === 12 ? specialUse(hex) : null,
      colon: bytes.join(":"),
      hyphen: bytes.join("-"),
      dotted: (hex.match(/.{4}/g) ?? []).join(".").toLowerCase(),
      bare: hex.toLowerCase(),
      eui64: hex.length === 12 ? toEui64(hex) : null,
    };
  }, [hex]);

  const tableRows = useMemo(() => {
    const needle = tableQuery.trim().toLowerCase();
    if (!needle) return OUI_TABLE;
    return OUI_TABLE.filter((entry) =>
      `${entry.oui} ${entry.vendor} ${entry.note ?? ""}`.toLowerCase().includes(needle),
    );
  }, [tableQuery]);

  const messageId = "mac-input-message";

  return (
    <ToolShell
      slug="mac-lookup"
      notes={
        <>
          <p>
            A MAC address is 48 bits, and it is split in two. The first 24 bits are the
            Organisationally Unique Identifier, bought from the IEEE by the manufacturer, and the last
            24 bits are whatever that manufacturer assigns to the individual interface. Twenty-four
            bits gives each OUI holder about sixteen million addresses, which is why large vendors own
            dozens of prefixes rather than one.
          </p>
          <p>
            Two bits in the very first octet change the meaning of everything after them. The least
            significant bit is I/G: zero for a unicast address aimed at one interface, one for a group
            address. The next bit up is U/L: zero means the address came out of a registered OUI, one
            means it was made up locally. Both are the low bits of the first octet when the address is
            written in hex, and both are the first bits on the wire, because Ethernet transmits each
            octet least significant bit first.
          </p>
          <p>
            A locally administered address is almost never a mystery, it is a hint. It usually means a
            virtual machine (QEMU and KVM use 52:54:00), a container (Docker's bridge hands out 02:42
            followed by the container's IP), a bonded or bridged interface that inherited a synthetic
            address, or a phone doing MAC randomisation. Every modern mobile operating system now
            generates a fresh locally administered address per Wi-Fi network by default, which is why
            MAC-based device tracking and MAC-based access control both stopped working reliably.
          </p>
          <p>
            The vendor table on this page holds roughly ninety prefixes chosen for how often they turn
            up, not for coverage. The IEEE Registration Authority publishes the authoritative list of
            every assignment, and that is what to check before putting a vendor attribution in a
            report. A lookup here that comes back empty means the prefix is not in this table, not
            that it is unassigned.
          </p>
        </>
      }
    >
      <div className="space-y-6">
        <ToolPanel title="Address">
          <label htmlFor="mac-input" className="block font-mono-tight text-sm text-[hsl(var(--brand-bone-dim))]">
            MAC address, in any common format, or just a 6-digit OUI
          </label>
          <input
            id="mac-input"
            type="text"
            value={raw}
            spellCheck={false}
            autoComplete="off"
            data-testid="input-mac"
            onChange={(event) => setRaw(event.target.value)}
            aria-invalid={parsed.kind === "error"}
            aria-describedby={parsed.kind === "error" || parsed.kind === "hint" ? messageId : undefined}
            placeholder="B8:27:EB:1A:2B:3C"
            className="mt-3 w-full rounded-lg border border-[hsl(var(--brand-iron))] bg-[hsl(var(--brand-obsidian)/0.6)] px-4 py-3 font-mono-tight text-sm text-[hsl(var(--brand-bone))] placeholder:text-[hsl(var(--brand-ash))] focus:border-[hsl(var(--brand-signal))] focus:outline-none"
          />

          {parsed.kind === "error" ? (
            <p
              id={messageId}
              role="alert"
              data-testid="text-mac-error"
              className="mt-3 flex gap-2 font-mono-tight text-xs leading-relaxed text-[hsl(var(--brand-danger))]"
            >
              <span aria-hidden="true">✕</span>
              <span>{parsed.message}</span>
            </p>
          ) : null}
          {parsed.kind === "hint" ? (
            <p id={messageId} className="mt-3 font-mono-tight text-xs text-[hsl(var(--brand-ash))]">
              {parsed.message}
            </p>
          ) : null}

          <div className="mt-4 flex flex-wrap gap-2">
            {["B8:27:EB:1A:2B:3C", "00-50-56-C0-00-08", "5254.00ab.cdef", "0242ac110002", "01:00:5E:7F:00:01"].map(
              (example) => (
                <button
                  key={example}
                  type="button"
                  onClick={() => setRaw(example)}
                  className="inline-flex min-h-[28px] items-center rounded-full border border-[hsl(var(--brand-iron))] px-3 py-1 font-mono-tight text-[10px] tracking-[0.12em] text-[hsl(var(--brand-ash))] transition-colors hover:border-[hsl(var(--brand-signal)/0.6)] hover:text-[hsl(var(--brand-bone))] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[hsl(var(--brand-signal))]"
                >
                  {example}
                </button>
              ),
            )}
          </div>
        </ToolPanel>

        {decoded ? (
          <>
            <div className="grid gap-6 md:grid-cols-2">
              <ToolPanel title="Normalised">
                {(
                  [
                    ["Colon", decoded.colon],
                    ["Hyphen", decoded.hyphen],
                    ["Cisco dotted", decoded.dotted],
                    ["Bare", decoded.bare],
                  ] as const
                ).map(([label, value]) => (
                  <div
                    key={label}
                    className="flex flex-wrap items-center justify-between gap-x-4 gap-y-2 border-b border-[hsl(var(--brand-iron)/0.5)] py-2.5 last:border-b-0"
                  >
                    <span className="font-mono-tight text-[10px] uppercase tracking-[0.28em] text-[hsl(var(--brand-ash))]">
                      {label}
                    </span>
                    <span className="flex items-center gap-2">
                      <span className="break-all font-mono-tight text-sm text-[hsl(var(--brand-bone))]">
                        {value}
                      </span>
                      <CopyButton value={value} label={`Copy ${label} form`} />
                    </span>
                  </div>
                ))}
              </ToolPanel>

              <ToolPanel title="Identity">
                <ToolResult label="OUI" value={decoded.oui} testId="text-oui" />
                <ToolResult
                  label="Vendor"
                  value={
                    decoded.entry ? (
                      decoded.entry.vendor
                    ) : (
                      <span className="text-[hsl(var(--brand-ash))]">Not in this table</span>
                    )
                  }
                  testId="text-vendor"
                />
                {decoded.entry?.note ? <ToolResult label="Note" value={decoded.entry.note} /> : null}
                {decoded.nic ? <ToolResult label="Device portion" value={decoded.nic} /> : null}
                {decoded.eui64 ? <ToolResult label="Modified EUI-64" value={decoded.eui64} /> : null}
              </ToolPanel>
            </div>

            <ToolPanel title="First octet">
              <div className="flex flex-wrap items-center gap-x-6 gap-y-4">
                <div>
                  <div className="font-mono-tight text-[10px] uppercase tracking-[0.28em] text-[hsl(var(--brand-ash))]">
                    0x{decoded.bytes[0]} in binary
                  </div>
                  <div className="mt-2 flex items-end gap-1" aria-hidden="true">
                    {decoded.firstBits.split("").map((bit, index) => {
                      const isUl = index === 6;
                      const isIg = index === 7;
                      return (
                        <div key={index} className="flex w-6 flex-col items-center">
                          <span
                            className={`font-mono-tight text-base leading-none ${
                              isUl || isIg
                                ? "text-[hsl(var(--brand-signal))]"
                                : "text-[hsl(var(--brand-bone-dim))]"
                            }`}
                          >
                            {bit}
                          </span>
                          <span className="mt-1 font-mono-tight text-[8px] uppercase tracking-[0.1em] text-[hsl(var(--brand-ash))]">
                            {isUl ? "U/L" : isIg ? "I/G" : `b${7 - index}`}
                          </span>
                        </div>
                      );
                    })}
                  </div>
                  <p className="sr-only">
                    First octet {decoded.bytes[0]} in binary is {decoded.firstBits}. Bit 1 is the U/L
                    bit and bit 0 is the I/G bit.
                  </p>
                </div>

                <div className="min-w-[220px] flex-1 space-y-3">
                  <div>
                    <div className="font-mono-tight text-[10px] uppercase tracking-[0.28em] text-[hsl(var(--brand-ash))]">
                      I/G bit ({decoded.multicast ? "1" : "0"})
                    </div>
                    <p
                      className="mt-1 font-mono-tight text-sm text-[hsl(var(--brand-bone))]"
                      data-testid="text-ig"
                    >
                      {decoded.multicast ? "Group address (multicast or broadcast)" : "Individual address (unicast)"}
                    </p>
                  </div>
                  <div>
                    <div className="font-mono-tight text-[10px] uppercase tracking-[0.28em] text-[hsl(var(--brand-ash))]">
                      U/L bit ({decoded.locallyAdministered ? "1" : "0"})
                    </div>
                    <p
                      className="mt-1 font-mono-tight text-sm text-[hsl(var(--brand-bone))]"
                      data-testid="text-ul"
                    >
                      {decoded.locallyAdministered
                        ? "Locally administered (not from a registered OUI)"
                        : "Globally unique (assigned from a registered OUI)"}
                    </p>
                  </div>
                </div>
              </div>

              {decoded.locallyAdministered ? (
                <p className="mt-5 rounded-lg border border-[hsl(var(--brand-amber)/0.4)] bg-[hsl(var(--brand-amber)/0.06)] p-4 font-mono-tight text-xs leading-relaxed text-[hsl(var(--brand-bone-dim))]">
                  <span aria-hidden="true">! </span>
                  The U/L bit is set, so this address was made up locally and the first three bytes
                  are not a registered OUI. Any vendor shown above is therefore a coincidence unless
                  it is a known convention. In practice a locally administered address means a virtual
                  machine, a container, a bridge or bond interface, or a phone using MAC
                  randomisation.
                </p>
              ) : null}

              {decoded.multicast && !decoded.special ? (
                <p className="mt-4 font-mono-tight text-xs leading-relaxed text-[hsl(var(--brand-bone-dim))]">
                  The I/G bit is set, so this is a group address. Switches flood it rather than
                  forwarding it to one port, unless IGMP or MLD snooping has learned who wants it.
                </p>
              ) : null}

              {decoded.special ? (
                <p className="mt-4 rounded-lg border border-[hsl(var(--brand-signal)/0.35)] bg-[hsl(var(--brand-signal)/0.06)] p-4 font-mono-tight text-xs leading-relaxed text-[hsl(var(--brand-bone-dim))]">
                  <span className="text-[hsl(var(--brand-signal))]">Known address: </span>
                  {decoded.special}
                </p>
              ) : null}
            </ToolPanel>
          </>
        ) : null}

        <ToolPanel title={`Vendor table (${OUI_TABLE.length} prefixes)`}>
          <label
            htmlFor="oui-search"
            className="block font-mono-tight text-sm text-[hsl(var(--brand-bone-dim))]"
          >
            Search the table by vendor or prefix
          </label>
          <input
            id="oui-search"
            type="search"
            value={tableQuery}
            spellCheck={false}
            autoComplete="off"
            data-testid="input-oui-search"
            onChange={(event) => setTableQuery(event.target.value)}
            placeholder="vmware, raspberry, 00:50"
            className="mt-3 w-full rounded-lg border border-[hsl(var(--brand-iron))] bg-[hsl(var(--brand-obsidian)/0.6)] px-4 py-3 font-mono-tight text-sm text-[hsl(var(--brand-bone))] placeholder:text-[hsl(var(--brand-ash))] focus:border-[hsl(var(--brand-signal))] focus:outline-none"
          />

          <div className="mt-5 overflow-x-auto">
            <table className="w-full min-w-[520px] border-collapse text-left">
              <caption className="sr-only">Curated OUI prefixes and the vendors they belong to</caption>
              <thead>
                <tr className="border-b border-[hsl(var(--brand-iron))]">
                  {["OUI", "Vendor", "Note"].map((head) => (
                    <th
                      key={head}
                      scope="col"
                      className="py-2 pr-4 font-mono-tight text-[10px] uppercase tracking-[0.28em] text-[hsl(var(--brand-ash))]"
                    >
                      {head}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {tableRows.map((entry) => (
                  <tr key={entry.oui} className="border-b border-[hsl(var(--brand-iron)/0.5)] align-top">
                    <th
                      scope="row"
                      className="whitespace-nowrap py-2 pr-4 text-left font-mono-tight text-sm font-normal text-[hsl(var(--brand-signal))]"
                    >
                      <button
                        type="button"
                        onClick={() => setRaw(entry.oui)}
                        className="min-h-[24px] py-1 underline decoration-[hsl(var(--brand-iron))] underline-offset-4 transition-colors hover:decoration-[hsl(var(--brand-signal))] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[hsl(var(--brand-signal))]"
                      >
                        {entry.oui}
                      </button>
                    </th>
                    <td className="py-2 pr-4 font-mono-tight text-sm text-[hsl(var(--brand-bone))]">
                      {entry.vendor}
                    </td>
                    <td className="py-2 pr-4 font-mono-tight text-xs leading-relaxed text-[hsl(var(--brand-bone-dim))]">
                      {entry.note ?? <span className="text-[hsl(var(--brand-iron))]">-</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {tableRows.length === 0 ? (
            <p className="mt-4 font-mono-tight text-sm text-[hsl(var(--brand-ash))]">
              Nothing in the table matches that search.
            </p>
          ) : null}

          <p className="mt-5 font-mono-tight text-xs leading-relaxed text-[hsl(var(--brand-ash))]">
            This is a curated subset, not the IEEE registry. The full assignment list is published by
            the IEEE Registration Authority, and that is the source to cite in anything that matters.
          </p>
        </ToolPanel>
      </div>
    </ToolShell>
  );
}
